"""
Alpha Finder — Gemini 1.5 Pro Prompt Templates (Phase 2)

Generated by prompt engineering agent.
Usage:
    from gemini_prompts import SYSTEM_PROMPT, build_user_prompt, RESPONSE_SCHEMA
"""

from datetime import datetime, timezone


# ─── System Prompt ─────────────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are a senior quantitative equity analyst with deep expertise in fundamental analysis, technical momentum, and competitive strategy. Your job is to produce concise, data-driven stock research briefs — the kind a hedge fund PM would read in 60 seconds before making a decision.

You will be given a structured data snapshot for a Nasdaq-listed stock that is currently outperforming the S&P 500 over the past 30 days. Your task is to analyze WHY this outperformance is happening, whether it is SUSTAINABLE, and what the key risks are.

CRITICAL RULES:
1. You MUST explicitly reference the provided data points (price performance, P/E ratios, revenue growth, volume trends, news headlines, etc.) in your reasoning. Do not speak in generalities.
2. Every claim must be traceable to either the injected data or well-established financial logic. No hallucinated facts.
3. Output ONLY a single, valid JSON object matching the schema provided. No markdown, no preamble, no explanation outside the JSON.
4. Be opinionated and specific. Vague, hedged non-answers lower the usefulness of this tool.
5. If the data is insufficient to support a claim, say so explicitly inside the relevant field — do not fabricate supporting evidence.
6. Calibrate your Alpha Score honestly. Reserve 8-10 for genuinely exceptional setups. Most stocks should score 4-7."""


# ─── User Prompt Builder ────────────────────────────────────────────────────────

def build_user_prompt(ticker_data: dict, news_headlines: list[dict]) -> str:
    """
    Builds the full Gemini user prompt for a single ticker.

    ticker_data keys expected (from scanner.py output):
        ticker, name, sector, industry, current_price, market_cap,
        pct_change_30d, spy_return_30d, relative_strength,
        pe_ratio, forward_pe, eps_ttm, revenue_growth,
        avg_volume, week_52_high, week_52_low

    news_headlines: list of {"date": "YYYY-MM-DD", "headline": "..."} dicts
    """
    t = ticker_data

    # Format market cap
    mc = t.get("market_cap") or 0
    if mc >= 1e12:
        mc_str = f"${mc/1e12:.2f}T"
    elif mc >= 1e9:
        mc_str = f"${mc/1e9:.2f}B"
    elif mc >= 1e6:
        mc_str = f"${mc/1e6:.1f}M"
    else:
        mc_str = f"${mc:,.0f}"

    # Format news
    if news_headlines:
        news_block = "\n".join(
            f"  [{h.get('date', 'N/A')}] {h.get('headline', '')}"
            for h in news_headlines[:10]
        )
    else:
        news_block = "  (no recent headlines available)"

    # Volume trend label
    avg_vol      = t.get("avg_volume", 0)
    recent_vol   = t.get("recent_volume", avg_vol)  # optional field
    if recent_vol and avg_vol:
        vol_ratio = recent_vol / avg_vol
        vol_trend = f"{'Above' if vol_ratio > 1.1 else 'Below' if vol_ratio < 0.9 else 'In-line'} average ({vol_ratio:.1f}x)"
    else:
        vol_trend = "N/A"

    return f"""Analyze the following stock and return a JSON research brief per the schema below.

--- INJECTED DATA SNAPSHOT ---
Ticker:                  {t.get('ticker', 'N/A')}
Company Name:            {t.get('name', 'N/A')}
Sector / Industry:       {t.get('sector', 'N/A')} / {t.get('industry', 'N/A')}
Current Price:           ${t.get('current_price', 'N/A')}
Market Cap:              {mc_str}

PERFORMANCE
  Stock 30-Day Return:   {t.get('pct_change_30d', 'N/A')}%
  SPY 30-Day Return:     {t.get('spy_return_30d', 'N/A')}%
  Relative Strength:     +{t.get('relative_strength', 'N/A')} pts vs SPY

FUNDAMENTALS
  P/E Ratio (TTM):       {t.get('pe_ratio') or 'N/A'}
  Forward P/E:           {t.get('forward_pe') or 'N/A'}
  EPS (TTM):             ${t.get('eps_ttm') or 'N/A'}
  Revenue Growth (YoY):  {f"{t['revenue_growth']*100:.1f}" if t.get('revenue_growth') else 'N/A'}%

TECHNICALS
  52-Week High:          ${t.get('week_52_high') or 'N/A'}
  52-Week Low:           ${t.get('week_52_low') or 'N/A'}
  Avg Daily Volume:      {t.get('avg_volume', 'N/A'):,} shares
  Volume Trend:          {vol_trend}

RECENT NEWS (chronological, oldest → newest)
{news_block}

--- ANALYSIS INSTRUCTIONS ---
Using ONLY the data above plus your financial knowledge, produce a JSON object with these fields:

1.  outperformance_drivers      — Why is {t.get('ticker')} beating SPY right now? Cite specific data points.
2.  fundamental_assessment      — Are the fundamentals (valuation, growth, earnings) supporting or contradicting the price move?
3.  technical_momentum          — What does price action, 52-week range positioning, and volume trend signal?
4.  moat_analysis               — What is the company's durable competitive advantage, if any? How strong is it?
5.  sustainability_verdict      — Is this outperformance likely to continue (3-6 month horizon) or is it a temporary spike? Give a clear verdict with reasoning.
6.  bull_case                   — The 2-3 strongest reasons a long position is justified right now.
7.  bear_case                   — The 2-3 most credible risks or reasons this trade fails.
8.  news_sentiment_summary      — Synthesize the tone and themes from the provided headlines. Flag any material events.
9.  alpha_score                 — Integer 1-10. See scoring rubric below.
10. alpha_score_rationale       — Explain the score in 2-3 sentences, referencing specific data.

ALPHA SCORE RUBRIC:
  9-10 : Exceptional setup — strong fundamentals, clear catalyst, high relative strength, sustainable momentum, low valuation risk
  7-8  : Good setup — most factors aligned, minor concerns
  5-6  : Mixed signals — some positives offset by notable risks or valuation stretch
  3-4  : Weak setup — outperformance likely temporary, fundamentals or momentum unconvincing
  1-2  : Avoid — red flags across multiple dimensions

Return ONLY the JSON object. No other text."""


# ─── Response JSON Schema ────────────────────────────────────────────────────────
# Pass this to genai.GenerativeModel(..., generation_config={"response_schema": RESPONSE_SCHEMA})
# when using Gemini's native JSON mode.

RESPONSE_SCHEMA = {
    "type": "object",
    "required": [
        "ticker", "company_name", "generated_at",
        "outperformance_drivers", "fundamental_assessment",
        "technical_momentum", "moat_analysis", "sustainability_verdict",
        "bull_case", "bear_case", "news_sentiment_summary",
        "alpha_score", "alpha_score_rationale"
    ],
    "properties": {
        "ticker":        {"type": "string"},
        "company_name":  {"type": "string"},
        "generated_at":  {"type": "string"},
        "outperformance_drivers": {
            "type": "object",
            "required": ["summary", "key_factors"],
            "properties": {
                "summary":     {"type": "string"},
                "key_factors": {"type": "array", "items": {"type": "string"}, "minItems": 1, "maxItems": 4},
            }
        },
        "fundamental_assessment": {
            "type": "object",
            "required": ["valuation_stance", "growth_quality", "earnings_quality", "summary"],
            "properties": {
                "valuation_stance": {"type": "string", "enum": ["cheap", "fair", "stretched", "expensive", "insufficient_data"]},
                "growth_quality":   {"type": "string", "enum": ["accelerating", "steady", "decelerating", "negative", "insufficient_data"]},
                "earnings_quality": {"type": "string", "enum": ["strong", "mixed", "weak", "insufficient_data"]},
                "summary":          {"type": "string"},
            }
        },
        "technical_momentum": {
            "type": "object",
            "required": ["range_position", "volume_signal", "momentum_label", "summary"],
            "properties": {
                "range_position": {"type": "string", "enum": ["near_52w_high", "mid_range", "near_52w_low", "at_52w_high", "at_52w_low"]},
                "volume_signal":  {"type": "string", "enum": ["accumulation", "distribution", "neutral", "insufficient_data"]},
                "momentum_label": {"type": "string", "enum": ["strong_bullish", "bullish", "neutral", "bearish", "strong_bearish"]},
                "summary":        {"type": "string"},
            }
        },
        "moat_analysis": {
            "type": "object",
            "required": ["moat_type", "moat_strength", "summary"],
            "properties": {
                "moat_type":     {"type": "string", "enum": ["network_effects", "switching_costs", "cost_advantage", "intangible_assets", "efficient_scale", "combination", "none_identified"]},
                "moat_strength": {"type": "string", "enum": ["wide", "narrow", "none", "uncertain"]},
                "summary":       {"type": "string"},
            }
        },
        "sustainability_verdict": {
            "type": "object",
            "required": ["verdict", "confidence", "reasoning"],
            "properties": {
                "verdict":    {"type": "string", "enum": ["likely_sustainable", "mixed", "likely_temporary"]},
                "confidence": {"type": "string", "enum": ["high", "medium", "low"]},
                "reasoning":  {"type": "string"},
            }
        },
        "bull_case": {"type": "array", "items": {"type": "string"}, "minItems": 2, "maxItems": 3},
        "bear_case": {"type": "array", "items": {"type": "string"}, "minItems": 2, "maxItems": 3},
        "news_sentiment_summary": {
            "type": "object",
            "required": ["overall_tone", "dominant_themes", "material_events", "summary"],
            "properties": {
                "overall_tone":     {"type": "string", "enum": ["strongly_positive", "positive", "neutral", "negative", "strongly_negative", "mixed"]},
                "dominant_themes":  {"type": "array", "items": {"type": "string"}, "maxItems": 3},
                "material_events":  {"type": "array", "items": {"type": "string"}},
                "summary":          {"type": "string"},
            }
        },
        "alpha_score":           {"type": "integer", "minimum": 1, "maximum": 10},
        "alpha_score_rationale": {"type": "string"},
    },
    "additionalProperties": False
}
